export default [
  "equals",
  "does not equal",
  "did equal",
  "did not equal",
  "does include",
  "does not include",
  "has changed",
  "has not changed",
  "is greater than",
  "is greater than or equal to",
  "is less than",
  "is less than or equal to",
  "is falsy",
  "is truthy",
]
